### PR TITLE
Implement basic layout

### PR DESCRIPTION
**Pull request by jjszaniszlo**
Begin work on basic layout, while I'm still learning how the xml works with javafx.

### CODE REVIEW

**Comment by jjszaniszlo** [comment]
the merge conflict for the main layout is because I made the mistake of removing that commit from this branch after cherry-picking it to main for you guys to use.  We can avoid this in the future by segregating changes better and by keeping cherry-picks in place.  usually there aren't many reasons to remove a commit for that.  They will merge as long as the hashes match

**Comment by jjszaniszlo** [comment]
please give me feedback on the basic layout ideas so I can resolve conflicts and merge.  I will implement the basic functionality within a different branch soon.  Remember that with styles we can also add themes and such to give it a more clean look.

**Comment by dominic-diblasio** [comment]
Looks like a simple add-in to me, so I agree with the general layout shared and would just recommend doing the changes to handle conflicts - a reminder that we can assign the roles in order to mitigate piling conflicts. If Federico agrees, go for it!

**Comment by jjszaniszlo** [comment]
to be honest, after a couple of hours of messing with the xml generator, I realized that its actually quite annoying to add custom components.  It's very possible, but you have to compile an independent jar file and import it.  So I may be just rolling javaFX raw similar to what @FedeBailaque  tried to do.  I will first merge these changes, so that we have at least something and then I will examine the feasibility of rolling my own component class structures.  I will have to make a lot of custom components for us because javaFX only comes shipped with the bare minimum.  So before I get on that, let's decide on a theme, color look and feel.  Ideally it should be easily changeable but it might be a pipe dream with our timeline and experience levels.  I will propose a few in the discord.

**Comment by jjszaniszlo** [comment]
Luckily, we will be able to get rid of 1 dependency if we ditch FXML...  So I will try to examine the feasibility of rolling our own components.  If not, there are dependencies we can introduce which implement a few components for us in JavaFX.

**Pull request merged**
